-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "breeze_cursors")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    general = {
        col = {
            active_border = {
                colors = {"rgba(613583ff)"},
                angle = 45,
            },
        },
    },
    gestures = {
        workspace_swipe_forever = false,
    },
})
